"""Single storage module for STATE, queue, and feedback — repo is source of truth."""
from store.machine import (
    ACTIVE_PHASES,
    InvalidTransition,
    LEGACY_MAP,
    PHASE_ARTIFACTS,
    PHASES,
    TRANSITIONS,
    active_article,
    artifact_exists,
    block,
    current_phase,
    resume,
    transition,
    unblock,
)
from store.feedback import (
    append_feedback,
    delete_feedback,
    feedback_dir,
    feedback_path,
    merge_feedback,
    read_feedback,
    remove_feedback,
    write_feedback,
)
from store.paths import article_dir, articles_root, repo_root, state_path
from store.queue import (
    SLUG_RE,
    TERMINAL_PHASES,
    article_is_merged,
    article_state_fields,
    article_state_path,
    delete_article_dir,
    load_queue,
    next_article,
    queue_with_states,
    remove_article_from_queue,
    save_queue,
    strip_queue_for_save,
    validate_slugs,
)
from store.state import (
    read_state,
    read_state_fields,
    write_state,
    write_state_fields,
)

__all__ = [
    "SLUG_RE",
    "TERMINAL_PHASES",
    "append_feedback",
    "article_dir",
    "article_is_merged",
    "article_state_fields",
    "article_state_path",
    "articles_root",
    "delete_article_dir",
    "delete_feedback",
    "feedback_dir",
    "feedback_path",
    "load_queue",
    "merge_feedback",
    "next_article",
    "queue_with_states",
    "read_feedback",
    "read_state",
    "read_state_fields",
    "remove_article_from_queue",
    "remove_feedback",
    "repo_root",
    "save_queue",
    "state_path",
    "strip_queue_for_save",
    "validate_slugs",
    "write_feedback",
    "write_state",
    "write_state_fields",
]
